// This file was automatically generated by AntennaVision v.0.1. Do not edit!
const configObjects = [
{
  "color": "#ffffff",
  "height": 1.0,
  "pos": [
    0.5,
    0.0,
    0.0
  ],
  "quat": [
    0.0,
    -0.0,
    -0.7071067811865475,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.005,
  "radius_top": 0.005,
  "type": "cylinder"
},
{
  "color": "#ff0000",
  "height": 0.16,
  "pos": [
    1.0,
    0.08,
    0.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#ff0000",
  "height": 0.04000000000000001,
  "pos": [
    1.0,
    0.18,
    0.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#008000",
  "height": 0.15999999999999992,
  "pos": [
    0.92,
    1.7763568394002505e-17,
    0.0
  ],
  "quat": [
    0.0,
    -0.0,
    0.7071067811865475,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#008000",
  "height": 0.040000000000000036,
  "pos": [
    0.8200000000000001,
    3.9968028886505634e-17,
    0.0
  ],
  "quat": [
    0.0,
    -0.0,
    0.7071067811865475,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#0000ff",
  "height": 0.16,
  "pos": [
    1.0,
    0.0,
    0.08
  ],
  "quat": [
    0.7071067811865475,
    -0.0,
    0.0,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#0000ff",
  "height": 0.04000000000000001,
  "pos": [
    1.0,
    0.0,
    0.18
  ],
  "quat": [
    0.7071067811865475,
    -0.0,
    0.0,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#ffffff",
  "height_segments": 8,
  "pos": [
    1.0,
    0.0,
    0.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radius": 0.010000000000000002,
  "type": "sphere",
  "width_segments": 16
},
{
  "color": "#ffffff",
  "height": 1.0,
  "pos": [
    1.0,
    0.5,
    0.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radial_segments": 8,
  "radius_bottom": 0.005,
  "radius_top": 0.005,
  "type": "cylinder"
},
{
  "color": "#ff0000",
  "height": 0.16,
  "pos": [
    1.0000000000000002,
    1.0,
    0.08
  ],
  "quat": [
    0.7071067811865475,
    -0.0,
    0.0,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#ff0000",
  "height": 0.04000000000000001,
  "pos": [
    1.0000000000000002,
    1.0,
    0.18
  ],
  "quat": [
    0.7071067811865475,
    -0.0,
    0.0,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#008000",
  "height": 0.15999999999999992,
  "pos": [
    0.9200000000000003,
    1.0,
    0.0
  ],
  "quat": [
    0.0,
    -0.0,
    0.7071067811865475,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#008000",
  "height": 0.040000000000000036,
  "pos": [
    0.8200000000000003,
    1.0,
    0.0
  ],
  "quat": [
    0.0,
    -0.0,
    0.7071067811865475,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#0000ff",
  "height": 0.15999999999999992,
  "pos": [
    1.0000000000000002,
    0.92,
    1.7763568394002505e-17
  ],
  "quat": [
    0.0,
    -0.0,
    -1.0,
    6.123233995736766e-17
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#0000ff",
  "height": 0.040000000000000036,
  "pos": [
    1.0000000000000002,
    0.8200000000000001,
    3.9968028886505634e-17
  ],
  "quat": [
    0.0,
    -0.0,
    -1.0,
    6.123233995736766e-17
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#ffffff",
  "height_segments": 8,
  "pos": [
    1.0000000000000002,
    1.0,
    0.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radius": 0.010000000000000002,
  "type": "sphere",
  "width_segments": 16
},
{
  "color": "#ffffff",
  "height": 1.0,
  "pos": [
    1.0,
    1.0,
    0.5
  ],
  "quat": [
    0.7071067811865475,
    -0.0,
    1.570092458683775e-16,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.005,
  "radius_top": 0.005,
  "type": "cylinder"
},
{
  "color": "#ff0000",
  "height": 0.15999999999999992,
  "pos": [
    1.08,
    1.0000000000000002,
    1.0
  ],
  "quat": [
    0.0,
    -0.0,
    -0.7071067811865475,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#ff0000",
  "height": 0.040000000000000036,
  "pos": [
    1.18,
    1.0000000000000002,
    1.0
  ],
  "quat": [
    0.0,
    -0.0,
    -0.7071067811865475,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#008000",
  "height": 0.15999999999999992,
  "pos": [
    1.0,
    1.08,
    1.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#008000",
  "height": 0.040000000000000036,
  "pos": [
    1.0,
    1.1800000000000002,
    1.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#0000ff",
  "height": 0.15999999999999992,
  "pos": [
    1.0,
    1.0000000000000002,
    1.08
  ],
  "quat": [
    0.7071067811865475,
    -0.0,
    0.0,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius_bottom": 0.004,
  "radius_top": 0.004,
  "type": "cylinder"
},
{
  "color": "#0000ff",
  "height": 0.040000000000000036,
  "pos": [
    1.0,
    1.0000000000000002,
    1.18
  ],
  "quat": [
    0.7071067811865475,
    -0.0,
    0.0,
    0.7071067811865476
  ],
  "radial_segments": 8,
  "radius": 0.020000000000000004,
  "type": "cone"
},
{
  "color": "#ffffff",
  "height_segments": 8,
  "pos": [
    1.0,
    1.0000000000000002,
    1.0
  ],
  "quat": [
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "radius": 0.010000000000000002,
  "type": "sphere",
  "width_segments": 16
},
];
