//
// Created by Tristan Krause on 2026-06-03.
//

#include "three.hpp"
#include <format>
#include <nlohmann/json.hpp>

#include "convert.hpp"
#include "manifest.hpp"
#include "math/coords.hpp"
#include "math/functions.hpp"

namespace
{
    [[nodiscard]] constexpr std::string hex_string_from_color(Color const color) { return std::format("#{:06x}", static_cast<std::uint32_t>(color)); }

    template <typename T, typename... Args>
    size_t total_size(const std::vector<T>& first, const Args&... rest)
    { return first.size() + (rest.size() + ...); }

    template <typename T, typename... Args>
    std::vector<T> concat_and_destroy(std::vector<T>&& first, Args&&... rest)
    {
        first.reserve(total_size(first, rest...));
        (..., first.insert(first.end(), std::make_move_iterator(rest.begin()), std::make_move_iterator(rest.end())));
        return std::move(first);
    }
} // namespace

namespace three
{
    void Container::add(json&& object) { this->objects.push_back(std::move(object)); }

    void Container::add(std::vector<json>&& new_objects)
    { this->objects.insert(this->objects.end(), std::make_move_iterator(new_objects.begin()), std::make_move_iterator(new_objects.end())); }

    void Container::export_to_javascript(std::filesystem::path const& p) const
    {
        std::ofstream ofs(p);
        ofs << "// This file was automatically generated by " << APPLICATION_NAME << " v." << convert::string_from_version(APPLICATION_VERSION) << ". Do not edit!\n";
        ofs << "const configObjects = [\n";
        for (auto const& object : objects) { ofs << object.dump(2) << ",\n"; }
        ofs << "];\n";
    }

    json make_line(std::vector<Pos> const& points, double const width, Color const color)
    {
        json js;
        std::vector<double> points_flat;
        points_flat.reserve(points.size() * 3);
        for (auto const point : points)
        {
            points_flat.push_back(point.x);
            points_flat.push_back(point.y);
            points_flat.push_back(point.z);
        }
        js["type"] = "line";
        js["color"] = hex_string_from_color(color);
        js["width"] = width;
        js["points"] = points_flat;
        return js;
    }

    json make_line(Pos pos_a, Pos pos_b, double const width, Color const color) { return make_line({pos_a, pos_b}, width, color); }

    json make_sphere(Pos const& pos, double const radius, Color const color, std::uint16_t const segments_width, std::uint16_t const segments_height)
    {
        json js;
        js["type"] = "sphere";
        js["color"] = hex_string_from_color(color);
        js["radius"] = radius;
        js["pos"] = pos.toNdArray().toStlVector();
        constexpr Quaternion quat{}; // unity quaternion
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["width_segments"] = segments_width;
        js["height_segments"] = segments_height;
        return js;
    }

    json make_cylinder(Pos const& pos_start,
        Pos const& pos_end,
        double const radius_start,
        double const radius_end,
        Color const color,
        std::uint16_t segments_radial)
    {
        json js;
        js["type"] = "cylinder";
        js["color"] = hex_string_from_color(color);
        auto const pos_center = (pos_start + pos_end) / 2.0;
        auto const direction = pos_end - pos_start;
        js["radius_top"] = radius_end;
        js["radius_bottom"] = radius_start;
        js["height"] = direction.norm();
        js["pos"] = pos_center.toNdArray().toStlVector();

        // default orientation of a cylinder in THREE is (0,1,0)
        auto const quat = math::quaternion_from_directions(Pos(0.0, 1.0, 0.0), direction);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["radial_segments"] = segments_radial;
        return js;
    }

    json make_cone(Pos const& pos_start, Pos const& pos_end, double const radius, Color const color, std::uint16_t segments_radial)
    {
        json js;
        js["type"] = "cone";
        js["color"] = hex_string_from_color(color);
        auto const pos_center = (pos_start + pos_end) / 2.0;
        auto const direction = pos_end - pos_start;
        js["radius"] = radius;
        js["height"] = direction.norm();
        js["pos"] = pos_center.toNdArray().toStlVector();

        // default orientation of a cone in THREE is (0,1,0)
        auto const quat = math::quaternion_from_directions(Pos(0.0, 1.0, 0.0), direction);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["radial_segments"] = segments_radial;
        return js;
    }

    json make_plane(Pos const& pos, Pos const& dir_target, double const width, double const height, double const angle, Color const color)
    {
        json js;
        js["type"] = "plane";
        js["color"] = hex_string_from_color(color);
        js["width"] = width;
        js["height"] = height;
        js["pos"] = pos.toNdArray().toStlVector();

        // default orientation of a plane in THREE is (0,0,1)
        auto const quat = Quaternion(dir_target, angle) * math::quaternion_from_directions(Pos(0.0, 0.0, 1.0), dir_target);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        return js;
    }

    std::vector<json>
    create_arrow(Pos const& pos_start, Pos const& pos_end, double const len_head, double const radius_line, double const radius_head, Color const color)
    {
        auto const pos_contact = pos_end + (pos_start - pos_end).normalize() * len_head;
        return {make_cylinder(pos_start, pos_contact, radius_line, radius_line, color), make_cone(pos_contact, pos_end, radius_head, color)};
    }

    std::vector<json> create_coordinate_arrows(Pos const& pos_center, Pos const& dir_x, Pos const& dir_y, Pos const& dir_z, double const len_arrow)
    {
        // auto objects_x = create_arrow(pos_center, pos_center + len_arrow * dir_x.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 * len_arrow,
        // Color::red); auto const objects_y = create_arrow(pos_center, pos_center + len_arrow * dir_y.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 *
        // len_arrow, Color::green); auto const objects_z = create_arrow(pos_center, pos_center + len_arrow * dir_z.normalize(), 0.2 * len_arrow, 0.02 *
        // len_arrow, 0.1 * len_arrow, Color::blue); std::vector const ball = {make_sphere(pos_center, 0.05 * len_arrow)}; return
        // concat_and_destroy(std::move(objects_x), objects_y, objects_z, ball);
        auto line_x = make_line(pos_center, pos_center + len_arrow * dir_x.normalize(), 2.0, Color::red);
        auto const line_y = make_line(pos_center, pos_center + len_arrow * dir_y.normalize(), 2.0, Color::lime);
        auto const line_z = make_line(pos_center, pos_center + len_arrow * dir_z.normalize(), 2.0, Color::blue);
        return {line_x, line_y, line_z};
    }

    std::vector<json> export_geometry(geometry::Geometry const& geo)
    {
        if (auto line = std::get_if<geometry::Line>(&geo))
        {
            return {make_line(line->pos_begin(), line->pos_end(), 2, Color::yellow)}; //
        }
        if (auto arc = std::get_if<geometry::CircleArc>(&geo))
        {
            std::vector<Pos> points(N_POINTS_THREE_CURVE);
            for (std::size_t k = 0; k < N_POINTS_THREE_CURVE; k++)
            {
                double t = math::nidx(k, N_POINTS_THREE_CURVE);
                points.at(k) = arc->pos_at(t);
            }
            return {make_line(points, 2, Color::yellow)};
        }
        return std::visit(
            [](const auto& g) -> std::vector<json>
            {
                if constexpr (std::constructible_from<geometry::Surface, decltype(g)>)
                {
                    auto const surface = geometry::Surface(g);
                    std::vector<json> objects = three::create_coordinate_arrows( //
                        geometry::surface::get_center(g),
                        geometry::surface::get_e1(g),
                        geometry::surface::get_e2(g),
                        geometry::surface::get_normal(g),
                        0.25 * std::sqrt(geometry::surface::get_area(g)) //
                    );
                    for (std::size_t k1 = 0; k1 < N_POINTS_THREE_SURFACE; k1++)
                    {
                        double const t1 = math::nidx(k1, N_POINTS_THREE_SURFACE);
                        std::vector<Pos> points(N_POINTS_THREE_SURFACE);
                        for (std::size_t k2 = 0; k2 < N_POINTS_THREE_SURFACE; k2++)
                        {
                            double const t2 = math::nidx(k2, N_POINTS_THREE_SURFACE);
                            points.at(k2) = geometry::surface::get_pos_at(surface, t1, t2);
                        }
                        objects.push_back(make_line(points, 2.0, Color::yellow));
                    }
                    for (std::size_t k2 = 0; k2 < N_POINTS_THREE_SURFACE; k2++)
                    {
                        double const t2 = math::nidx(k2, N_POINTS_THREE_SURFACE);
                        std::vector<Pos> points(N_POINTS_THREE_SURFACE);
                        for (std::size_t k1 = 0; k1 < N_POINTS_THREE_SURFACE; k1++)
                        {
                            double const t1 = math::nidx(k1, N_POINTS_THREE_SURFACE);
                            points.at(k1) = geometry::surface::get_pos_at(surface, t1, t2);
                        }
                        objects.push_back(make_line(points, 2.0, Color::yellow));
                    }
                    return objects;
                }
                else
                    throw SimulationError("Invalid geometry object");
            },
            geo);
    }

    void export_context(Context const& ctx, double system_wavelength, std::filesystem::path const& path_objects)
    {
        Container container;
        for (auto const& reference : ctx.references)
        {
            if (!reference.origin) { continue; } // we skip the dummy reference
            auto const pos_center = reference.global_from_local_pos(POS_ZERO);
            auto const pos_origin = reference.origin->global_from_local_pos(POS_ZERO);
            // auto const distance = (pos_center - pos_origin).norm();
            container.add(three::make_line(pos_origin, pos_center, 1.0, Color::white));
            container.add(three::create_coordinate_arrows(pos_center,
                reference.global_from_local_pos({1, 0, 0}) - pos_center,
                reference.global_from_local_pos({0, 1, 0}) - pos_center,
                reference.global_from_local_pos({0, 0, 1}) - pos_center,
                0.25 * system_wavelength));
        }

        auto add_radiator = [&container, &system_wavelength](components::Radiator const& radiator)
        {
            auto pos_center = radiator.origin->global_from_local_pos(POS_ZERO);
            double const radiator_length = 0.49 * system_wavelength;
            auto pos_end = radiator.origin->global_from_local_pos({0.0, 0.0, 0.5 * radiator_length});
            auto const pos_start = pos_center - (pos_end - pos_center);
            double const radius = 0.1 * radiator_length;
            container.add(make_cylinder(pos_start, pos_end, radius, radius, Color::white));
        };
        for (auto const& ant : ctx.antennas)
        {
            ant.visit(
                [&](auto const& ant)
                {
                    using Type = std::decay_t<decltype(ant)>;
                    if constexpr (std::is_same_v<Type, components::Radiator>) { add_radiator(ant); }
                    else if constexpr (std::is_same_v<Type, components::RadiatorArray>)
                    {
                        for (auto const& element : ant.elements) { add_radiator(element); }
                    }
                    else
                    {
                        throw SimulationError("Invalid antenna type");
                    }
                });
        }

        for (auto const& geo : ctx.geometries) container.add(three::export_geometry(geo));
        container.export_to_javascript(path_objects);
    }

} // namespace three
