//
// Created by Tristan Krause on 2026-06-03.
//

#include "three.hpp"
#include <format>
#include <nlohmann/json.hpp>
#include "manifest.hpp"
#include "math.hpp"

namespace
{
    [[nodiscard]] constexpr std::string hex_string_from_color(Color const color)
    {
        return std::format("#{:06x}", static_cast<std::uint32_t>(color));
    }

    template <typename T, typename... Args>
    size_t total_size(const std::vector<T>& first, const Args&... rest)
    { return first.size() + (rest.size() + ...); }

    template <typename T, typename... Args>
    std::vector<T> concat_and_destroy(std::vector<T>&& first, Args&&... rest)
    {
        first.reserve(total_size(first, rest...));
        (..., first.insert(first.end(), std::make_move_iterator(rest.begin()), std::make_move_iterator(rest.end())));
        return std::move(first);
    }
} // namespace

namespace three
{
    void Container::add(json&& object) { this->objects.push_back(std::move(object)); }

    void Container::add(std::vector<json>&& new_objects) { this->objects.insert(this->objects.end(), std::make_move_iterator(new_objects.begin()), std::make_move_iterator(new_objects.end())); }

    void Container::export_to_javascript(std::filesystem::path const& p) const
    {
        std::ofstream ofs(p);
        ofs << "// This file was automatically generated by " << APPLICATION_NAME << " v." << APPLICATION_VERSION << ". Do not edit!\n";
        ofs << "const configObjects = [\n";
        for (auto const& object : objects) { ofs << object.dump(2) << ",\n"; }
        ofs << "];\n";
    }

    json make_line(std::vector<pos_t> const& points, double const width, Color const color)
    {
        json js;
        std::vector<double> points_flat;
        points_flat.reserve(points.size() * 3);
        for (auto const point : points)
        {
            points_flat.push_back(point.x);
            points_flat.push_back(point.y);
            points_flat.push_back(point.z);
        }
        js["type"] = "line";
        js["color"] = hex_string_from_color(color);
        js["width"] = width;
        js["points"] = points_flat;
        return js;
    }

    json make_line(pos_t pos_a, pos_t pos_b, double const width, Color const color)
    {
        return make_line({pos_a, pos_b}, width, color);
    }

    json make_sphere(pos_t const& pos, double const radius, Color const color, std::uint16_t const segments_width, std::uint16_t const segments_height)
    {
        json js;
        js["type"] = "sphere";
        js["color"] = hex_string_from_color(color);
        js["radius"] = radius;
        js["pos"] = pos.toNdArray().toStlVector();
        constexpr Quaternion quat{}; // unity quaternion
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["width_segments"] = segments_width;
        js["height_segments"] = segments_height;
        return js;
    }

    json make_cylinder(pos_t const& pos_start, pos_t const& pos_end, double const radius_start, double const radius_end, Color const color, std::uint16_t segments_radial)
    {
        json js;
        js["type"] = "cylinder";
        js["color"] = hex_string_from_color(color);
        auto const pos_center = (pos_start + pos_end) / 2.0;
        auto const direction = pos_end - pos_start;
        js["radius_top"] = radius_end;
        js["radius_bottom"] = radius_start;
        js["height"] = direction.norm();
        js["pos"] = pos_center.toNdArray().toStlVector();

        // default orientation of a cylinder in THREE is (0,1,0)
        auto const quat = math::quaternion_from_directions(pos_t(0.0, 1.0, 0.0), direction);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["radial_segments"] = segments_radial;
        return js;
    }

    json make_cone(pos_t const& pos_start, pos_t const& pos_end, double const radius, Color const color, std::uint16_t segments_radial)
    {
        json js;
        js["type"] = "cone";
        js["color"] = hex_string_from_color(color);
        auto const pos_center = (pos_start + pos_end) / 2.0;
        auto const direction = pos_end - pos_start;
        js["radius"] = radius;
        js["height"] = direction.norm();
        js["pos"] = pos_center.toNdArray().toStlVector();

        // default orientation of a cone in THREE is (0,1,0)
        auto const quat = math::quaternion_from_directions(pos_t(0.0, 1.0, 0.0), direction);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["radial_segments"] = segments_radial;
        return js;
    }

    json make_plane(pos_t const& pos, pos_t const& dir_target, double const width, double const height, double const angle, Color const color)
    {
        json js;
        js["type"] = "plane";
        js["color"] = hex_string_from_color(color);
        js["width"] = width;
        js["height"] = height;
        js["pos"] = pos.toNdArray().toStlVector();

        // default orientation of a plane in THREE is (0,0,1)
        auto const quat = Quaternion(dir_target, angle) * math::quaternion_from_directions(pos_t(0.0, 0.0, 1.0), dir_target);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        return js;
    }

    std::vector<json> create_arrow(pos_t const& pos_start, pos_t const& pos_end, double const len_head, double const radius_line, double const radius_head, Color const color)
    {
        auto const pos_contact = pos_end + (pos_start - pos_end).normalize() * len_head;
        return {make_cylinder(pos_start, pos_contact, radius_line, radius_line, color), make_cone(pos_contact, pos_end, radius_head, color)};
    }

    std::vector<json> create_coordinate_arrows(pos_t const& pos_center, pos_t const& dir_x, pos_t const& dir_y, pos_t const& dir_z, double const len_arrow)
    {
        // auto objects_x = create_arrow(pos_center, pos_center + len_arrow * dir_x.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 * len_arrow, Color::red);
        // auto const objects_y = create_arrow(pos_center, pos_center + len_arrow * dir_y.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 * len_arrow, Color::green);
        // auto const objects_z = create_arrow(pos_center, pos_center + len_arrow * dir_z.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 * len_arrow, Color::blue);
        // std::vector const ball = {make_sphere(pos_center, 0.05 * len_arrow)};
        // return concat_and_destroy(std::move(objects_x), objects_y, objects_z, ball);
        auto line_x = make_line(pos_center, pos_center + len_arrow * dir_x.normalize(), 2.0, Color::red);
        auto const line_y = make_line(pos_center, pos_center + len_arrow * dir_y.normalize(), 2.0, Color::lime);
        auto const line_z = make_line(pos_center, pos_center + len_arrow * dir_z.normalize(), 2.0, Color::blue);
        return {line_x, line_y, line_z};
    }

} // namespace three
