//
// Created by Tristan Krause on 2026-06-03.
//

#include "three.hpp"
#include <format>
#include <nlohmann/json.hpp>
#include "math.hpp"
#include "manifest.hpp"

namespace
{
    [[nodiscard]] std::string hex_string_from_color(fmt::color const color)
    {
        fmt::rgb rgb(color);
        return std::format("#{:02x}{:02x}{:02x}", rgb.r, rgb.g, rgb.b);
    }

    template <typename T, typename... Args>
    size_t total_size(const std::vector<T> &first, const Args &...rest)
    { return first.size() + (rest.size() + ...); }

    template <typename T, typename... Args>
    std::vector<T> concat_and_destroy(std::vector<T> &&first, Args &&...rest)
    {
        first.reserve(total_size(first, rest...));
        (..., first.insert(first.end(), std::make_move_iterator(rest.begin()), std::make_move_iterator(rest.end())));
        return std::move(first);
    }
} // namespace

namespace three
{
    void Container::add(json &&object) { this->objects.push_back(std::move(object)); }

    void Container::add(std::vector<json> &&objects) { this->objects.insert(this->objects.end(), std::make_move_iterator(objects.begin()), std::make_move_iterator(objects.end())); }

    void Container::export_to_javascript(std::filesystem::path const &p) const
    {
        std::ofstream ofs(p);
        ofs << "// This file was automatically generated by " << APPLICATION_NAME << " v." << APPLICATION_VERSION << ". Do not edit!\n";
        ofs << "const configObjects = [\n";
        for (auto const &object : objects) { ofs << object.dump(2) << ",\n"; }
        ofs << "];\n";
    }

    json make_sphere(Vec3 const &pos, double const radius, fmt::color const color, std::uint16_t const segments_width, std::uint16_t const segments_height)
    {
        json js;
        js["type"] = "sphere";
        js["color"] = hex_string_from_color(color);
        js["radius"] = radius;
        js["pos"] = pos.toNdArray().toStlVector();
        constexpr Quaternion quat{}; // unity quaternion
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["width_segments"] = segments_width;
        js["height_segments"] = segments_height;
        return js;
    }

    json make_cylinder(Vec3 const &pos_start, Vec3 const &pos_end, double const radius_start, double const radius_end, fmt::color const color, std::uint16_t segments_radial)
    {
        json js;
        js["type"] = "cylinder";
        js["color"] = hex_string_from_color(color);
        auto const pos_center = (pos_start + pos_end) / 2.0;
        auto const direction = pos_end - pos_start;
        js["radius_top"] = radius_end;
        js["radius_bottom"] = radius_start;
        js["height"] = direction.norm();
        js["pos"] = pos_center.toNdArray().toStlVector();

        // default orientation of a cylinder in THREE is (0,1,0)
        auto const quat = math::quaternion_from_directions(Vec3(0.0, 1.0, 0.0), direction);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["radial_segments"] = segments_radial;
        return js;
    }

    json make_cone(Vec3 const &pos_start, Vec3 const &pos_end, double const radius, fmt::color const color, std::uint16_t segments_radial)
    {
        json js;
        js["type"] = "cone";
        js["color"] = hex_string_from_color(color);
        auto const pos_center = (pos_start + pos_end) / 2.0;
        auto const direction = pos_end - pos_start;
        js["radius"] = radius;
        js["height"] = direction.norm();
        js["pos"] = pos_center.toNdArray().toStlVector();

        // default orientation of a cone in THREE is (0,1,0)
        auto const quat = math::quaternion_from_directions(Vec3(0.0, 1.0, 0.0), direction);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        js["radial_segments"] = segments_radial;
        return js;
    }

    json make_plane(Vec3 const &pos, Vec3 const &dir_target, double const width, double const height, double const angle, fmt::color const color)
    {
        json js;
        js["type"] = "plane";
        js["color"] = hex_string_from_color(color);
        js["width"] = width;
        js["height"] = height;
        js["pos"] = pos.toNdArray().toStlVector();

        // default orientation of a plane in THREE is (0,0,1)
        auto const quat = Quaternion(dir_target, angle) * math::quaternion_from_directions(Vec3(0.0, 0.0, 1.0), dir_target);
        js["quat"] = {quat.i(), quat.j(), quat.k(), quat.s()};
        return js;
    }

    std::vector<json> create_arrow(Vec3 const &pos_start, Vec3 const &pos_end, double const len_head, double const radius_line, double const radius_head, fmt::color const color)
    {
        auto const pos_contact = pos_end + (pos_start - pos_end).normalize() * len_head;
        return {make_cylinder(pos_start, pos_contact, radius_line, radius_line, color), make_cone(pos_contact, pos_end, radius_head, color)};
    }

    std::vector<json> create_coordinate_arrows(Vec3 const &pos_center, Vec3 const &dir_x, Vec3 const &dir_y, Vec3 const &dir_z, double const len_arrow)
    {
        auto objects_x = create_arrow(pos_center, pos_center + len_arrow * dir_x.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 * len_arrow, fmt::color::red);
        auto const objects_y = create_arrow(pos_center, pos_center + len_arrow * dir_y.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 * len_arrow, fmt::color::green);
        auto const objects_z = create_arrow(pos_center, pos_center + len_arrow * dir_z.normalize(), 0.2 * len_arrow, 0.02 * len_arrow, 0.1 * len_arrow, fmt::color::blue);
        std::vector const ball = {make_sphere(pos_center, 0.05 * len_arrow)};
        return concat_and_destroy(std::move(objects_x), objects_y, objects_z, ball);
    }

} // namespace three
